services:
  - type: web
    name: ml-trading-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python tradingbot.py
    envVars:
      - key: API_KEY
        sync: false
      - key: API_SECRET
        sync: false
      - key: BASE_URL
        value: https://paper-api.alpaca.markets
